name=library
version=1.0.0
author=mobius
maintainer=mobius
sentence=Arduino libary
paragraph=
category=Sensors
url=
architectures=*
includes=kinematics.h
# dot_a_linkage=true
precompiled=true